### ISSUE TITLE
Mono?

### ISSUE THREAD

**Issue by goofballLogic** [Jgraham2/NewsDemo#1]
Hi Justin,

Just trying to get this codebase up and running, but it doesn't seem to compile in my Visual Studio install.

I note that the README states "Mono's ASP.NET" is a pre-requisite, but there's no instruction about how to get this pre-requisite in place. I tried googling it and ended up at http://www.mono-project.com/docs/web/aspnet/ but again their didn't seem to be much in the way of getting started guides there. 

Given that Mono is a fairly unusual choice for running C# these days (cross-platform now available via .NET Core), perhaps you could include a guide to getting the solution up and running?

**Comment by Jgraham2** [comment]
Hi 

I created the project on VS for mac. And mono comes part and parceled with VS mac. I never used it myself eirher but was interest to see what it would do. I can try running it on a windows machine to see how i can get it to run and get back to you. Failing that i will just switch out for .net core

**Comment by goofballLogic** [comment]
Ah ok I have a mac available but I only have VS Code installed on it. What version of Visual Studio are you using on your Mac?

⁣Sent from TypeApp ​

**Comment by Jgraham2** [comment]
Hi

Yeah, I'm using Visual Studio Community 2017 for Mac.

**Comment by goofballLogic** [comment]
I managed to get this working with a few hacks on visual studio community 2017 for Mac!
